name: tyba_frotend_engineer_test
description: Tyba Frontend Engineer test

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  animate_do: ^2.1.0
  logger: ^1.1.0
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  animations: ^2.0.3
  json_annotation: ^4.5.0
  injectable: ^1.5.3
  intl: ^0.17.0
  flutter_svg: ^1.1.0
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  flutter_localizations:
    sdk: flutter
  json_utilities:
    git:
      url: https://github.com/FabianVarela/json_utilities
  flutter_hooks: ^0.18.2
  flutter_staggered_grid_view: ^0.6.1
  collection: ^1.16.0
  formz: ^0.4.1
  hooks_riverpod: ^1.0.4
  flutter_inappwebview: ^5.3.2
  go_router: ^3.1.1
  easy_localization: ^3.0.1
  expand_widget: ^2.1.0
  very_good_analysis: ^3.0.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/icons/
    - assets/images/
    - locale/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 300
          style: italic